package by.andersen.entity;

import by.andersen.annotations.AutoGenerated;
import by.andersen.enums.UserRole;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

@Getter
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@Builder
public class User implements Identifiable<Long>, Serializable {
  @AutoGenerated
  private Long id;
  private String name;
  private UserRole role;
  private String passwordHash;

  @Override
  public Long getId() {
    return id;
  }
}
