name: Maven CI/CD

on:
  push:
    branches: [ workshop_14 ]
  pull_request:
    branches: [ workshop_14 ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coworkingspace

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Build project with Maven
        run: mvn -B package --file pom.xml